---
title: "Read"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: show
    number_sections: TRUE
---

# SET-UP

```{r markdown, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, fig.align = "center", fig.width = 9, fig.height = 6)
options(width = 140)
```    

```{r settings, message = F}
source('0.0_settings.R')
```

# LENGTH-FREQUENCIES
```{r lf, message = F}
lfR <- paste0(dir.rdat, "lf.Rdata")

if(!file.exists(lfR)){
    lf <- get.lf(species='maquereau',user=imlp.user,password=imlp.pass)
    
    # length: m to mm, consistent 5mm bins
    lf$length <-roundFish(lf$length*1000,5) # idem to carbio before
    
    # temporary correction for 2022: will be cleaned in the future!!!
    lf[lf$sample.id==70450,'date'] <- as.Date("2022-09-02")
    lf[lf$sample.id %in% c(69829,69830,69931),'sample.id'] <- 69829
    lf[lf$sample.id %in% 70231,'source'] <- 91
    
    save(lf, file = lfR)
}else{
    load(lfR)
}

# Creation time
df <- file.info(list.files(dir.rdat, full.names = T,pattern="lf"))
df[which.max(df$mtime),'mtime']
```

# CATCH
Use the landings data compiled and checked in iml-assess/1.0_landings.
Save it again in this project to ensure a "fixed in time" file and easier access.
Add landings from S52 license
```{r catch, message = F,results=F}
# landings from S52 licenses (preliminary for NL)
source('scripts/1.3_lf_year.R')

# other landings
setwd('..')                                                                 
load(paste0('./01.0_landings/Rdata/',tail(my.year,1),'/catch.Rdata'))

catch <- rbind(catch,catch.sam)

save(catch,file=paste0('./02.0_catch-at-age/Rdata/',tail(my.year,1),'/catch.Rdata'))
```

# BIO
```{r bio, message = F}
bioR <- paste0(dir.rdat, "bio.Rdata")

if(!file.exists(bioR)){
    bio <- get.bio(species='maquereau',user=imlp.user,password=imlp.pass)
    
    # length column
    bio$length.fresh <- NULL # never the case
    names(bio)[12] <- 'length'  # frozen length = length
    
    # length: m to mm, consistent 5mm bins
    bio$length <- bio$length*1000 # idem to carbio before
    
    # correct mistakes
    bio[bio$nafo=='4WE','nafo'] <- '4W'
    
    # save
    save(bio, file = bioR)
}else{
    load(bioR)
}

# Creation time
df <- file.info(list.files(dir.rdat, full.names = T,pattern="bio"))
df[which.max(df$mtime),'mtime']
```


# Plots
Get a feel of what is in bio and lf data through plots of all length-freqs.
```{r plotdist, message = F}
check.lfdistribution <- FALSE
check.biodistribution <- FALSE

# was there a subsample?
lf$subsample <- ifelse(lf$sample.id %in% unique(bio$sample.id),TRUE,FALSE)

# has bio and associated lf?
bio$subsample <- ifelse(bio$sample.id %in% unique(lf$sample.id),TRUE,FALSE)
   
# check distributions
if(check.biodistribution) source('scripts/1.1_lf_distribution.R')
if(check.biodistribution) source('scripts/1.2_bio_distribution.R')
```




