---
title: "Catch-at-age: by gear"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: show
    number_sections: TRUE
---
    
# Catch-at-age: by gear
    
# SET-UP
```{r markdown, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, fig.align = "center", fig.width = 9, fig.height = 6)
options(width = 140)
```    

## settings
```{r settings, message = F}
source('0.0_settings.R')
```

## load all data
```{r data, message = F}
load(paste0(dir.rdat, "catch.caa.Rdata"))
load(paste0(dir.rdat, "lf.caa.Rdata"))
load(paste0(dir.rdat, "bio.caa.Rdata"))
load(paste0(dir.rdat, "lw.mod.Rdata"))
lf.caa[,which(names(lf.caa) %in% names(lw.mod)[-c(1:2)])] <- NULL       # remove model details
catch.caa <- catch.caa[catch.caa$year %in% unique(lf.caa$year),]        # years for which bio/lf
```

# CATCH-AT-AGE BY GEAR

```{r caa gear, message = F, fig.height = 6,fig.width = 8}
catch.diffused.gearR <- paste0(dir.rdat, "catch.diffused.gear.Rdata")
caa.gearR <- paste0(dir.rdat, "caa.gear.Rdata")

these.gear <- c("Seines_Nets_Traps_Weirs", "Gillnets", "Lines")

if(!all(file.exists(c(catch.diffused.gearR,caa.gearR)))){
    # step 1) get samples
    
    catch.diffused.gear <- ldply(these.gear,function(x){
        print(x)
        
        years <- my.year[my.year>=1976 & my.year %in% unique(lf.caa[lf.caa$gear==x,'year'])] 
        
        lf.gear <- lf.caa[lf.caa$gear==x & !is.na(lf.caa$gear) & lf.caa$year %in% years,]
        al.gear <- bio.caa[bio.caa$gear==x & !is.na(bio.caa$gear) & bio.caa$year %in% years,]
        ca.gear <- catch.caa[catch.caa$gear==x & !is.na(catch.caa$gear) & catch.caa$year %in% years,]
        
        catch.diffused <- get.samples(catch=ca.gear,
                                      lf=lf.gear, 
                                      al=al.gear,
                                      min.lf.samples =2,          # min samples for length-frequency
                                      min.al.samples =2,          # min samples for age-length key
                                      min.al.fish = 12,
                                      period.unit='quarter')   # quarterly grouping instead of monthly
        
        catch.diffused$age.0 <- NULL                                             # remove age 0 ?? (total landings somewhat smaller)
        catch.diffused <- catch.diffused[catch.diffused$length!=-1,]           # remove instances where threshold not reached (CAA will only represent part of catch; see checks later)
        catch.diffused <- catch.diffused[catch.diffused$option.lengthfreq<7,]  # don't allow to take info neighboring years for length frequencies (but yes for age length)
        return(catch.diffused)
    })
    save(catch.diffused.gear, file =  catch.diffused.gearR)
    
    caa.gear <- ddply(catch.diffused.gear,c('gear'),function(x){x[is.na(x)]<-0;get.caa(x,plus=10)})
    
    save(caa.gear, file =  caa.gearR)
}else{ 
    load(caa.gearR)
    load(catch.diffused.gearR)
}

```

## CHECK {.tabset}
### samples
```{r caa check samples, fig.height = 6,fig.width = 12}
check <- ddply(catch.diffused.gear,c('id','gear'),summarise,
               option.lengthfreq=unique(option.lengthfreq),
               nsample.lengthfreq=unique(nsample.lengthfreq),
               nfish.lengthfreq=sum(n.lf),
               option.agelength=unique(option.agelength),
               nsample.agelength=unique(nsample.agelength),
               nfish.agekey=sum(n.al))
check <- reshape2::melt(check,id=c('id','gear'))
ggplot(check,aes(x=value))+geom_histogram(bins=30)+facet_grid(gear~variable,scale='free')  
```

### total

```{r caa check total, fig.height = 3,fig.width = 10}
tot <- ddply(catch.caa[catch.caa$gear %in% these.gear,],c('year','gear'),summarise,catch=sum(catch))
ggplot(caa.gear,aes(x=year))+
    geom_bar(stat='identity',aes(y=caaw,fill=as.factor(age)))+
    geom_line(data=tot,aes(y=catch),size=1)+
    facet_wrap(~gear,scale='free_y',)+
    scale_fill_viridis_d()+
    labs(y="Landings (t)",x='Year',fill='Age')+
    scale_y_continuous(expand=c(0,0))
```

# PLOTS {.tabset}
## CAAN abs
```{r caan plot, message = F, fig.height = 6,fig.width = 8}
ggplot(caa.gear,aes(x=year,y=age,size=caan))+
    geom_point(alpha=0.8)+ scale_size(range = c(1,10))+
    facet_wrap(~gear,ncol=1)+
    scale_y_continuous(breaks=min(caa.gear$age):max(caa.gear$age))
```

## CAAN rel
```{r caan rel, message = F, fig.height = 6,fig.width = 8}
df <- caa.gear[!is.na(caa.gear$caan),]
df <- ddply(df,c('year','gear'),mutate,caan.rel=caan/max(caan))
ggplot(df,aes(x=year,y=age,size=caan.rel))+
    geom_point(alpha=0.8)+ 
    scale_size(range = c(1,6))+
    facet_wrap(~gear,ncol=1)+
    scale_y_continuous(breaks=min(df$age):max(df$age))
```

## CAAN arrow
```{r caan arrow, message = F, fig.height = 6,fig.width = 8}
df <- caa.gear[!is.na(caa.gear$caan),]
df <- ddply(df,c('year','gear'),mutate,caan.rel=caan/max(caan))

# autodetermine cohorts
m <- acast(df[df$gear=='Gillnets',],age~year,value.var = 'caan.rel')
a <- cohort(m)
a <- a[a$strength>=quantile(a$strength, 0.85, na.rm=TRUE),]   # 15% strongest years in the southern gulf
a$year <- a$year + min(df$age)
a$age <- min(df$age)
a$agemax <- max(df$age)
a$yearend <- a$year+max(df$age)-min(df$age)
a$label <- a$year-1

# just select some myself
a <- data.frame(year = c(1976, 1983, 1989, 2000), # four largest peaks according to assessment
                age = c(2, 1, 1, 1), 
                agemax = c(10, 10, 10, 10), 
                yearend = c(1984,1992, 1998, 2009),
                label = c(1978, 1982, 1988, 1999))

ggplot(df,aes(x=year,y=age))+
    geom_point(alpha=0.8,aes(size=caan.rel))+ 
    scale_size(range = c(1,7))+
    facet_wrap(~gear,ncol=1)+
    geom_segment(data=a,aes(xend=yearend,yend=agemax),col='red',linewidth=1)+
    geom_text(data=a,aes(x=yearend,y=agemax,label=label),col='red',size=3,hjust=0,vjust=-1)+
    coord_cartesian(xlim=range(df$year),clip='off')+
    scale_y_continuous(breaks=min(caa.gear$age):max(caa.gear$age))+
    labs(x='Year',y='Age',size='')
```

## CAAW
```{r caaw plot, message = F, fig.height = 6,fig.width = 8}
ggplot(caa.gear,aes(x=year,y=age,size=caaw))+
    geom_point(alpha=0.8)+ scale_size(range = c(1,10))+
    facet_wrap(~gear,ncol=1)+
    scale_y_continuous(breaks=min(caa.gear$age):max(caa.gear$age))
```

## WAA
```{r waa plot, message = F, fig.height = 6,fig.width = 8}
ggplot(caa.gear,aes(x=year,y=waa,group=age))+
    geom_line(aes(color=age),size=1)+
    facet_wrap(~gear,ncol=1)+
    scale_color_viridis()
```

