---
title: "Catch-at-age: assessment plots"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: show
    number_sections: TRUE
---
    
# SET-UP
```{r  markdown, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, fig.align = "center", fig.width = 9, fig.height = 6)
options(width = 140)
```    

## settings
```{r settings, message = F}
source('0.0_settings.R')
```

## load all data
```{r data, message = F}
load(paste0(dir.rdat, "caa.Rdata"))
load(paste0(dir.rdat, "catch.caa.Rdata"))
load(paste0(dir.rdat, "lf.caa.Rdata"))
load(paste0(dir.rdat, "bio.caa.Rdata"))
```

# Input data plot 
```{r plot_input, message = F, fig.height = 8,fig.width = 20}
bio.caa$id <- with(bio.caa,paste(sample.id,year,period,region,gear),collapse='.')
bio.in <- ddply(bio.caa,c('year','period','region','gear'),summarise,n=length(id),N=length(unique(id)))
bio.in$input <- 'bio'

lf.caa$id <- with(lf.caa,paste(sample.id,year,period,region,gear),collapse='.')
lf.in <- ddply(lf.caa,c('year','period','region','gear'),summarise,n=length(id),N=length(unique(id)))
lf.in$input <- 'lf'

names(catch.caa)[5] <- 'N'
catch.caa$input <- 'catch'

cols <- c("year","period","region","gear","N","input")
all <- rbind(catch.caa[,cols],lf.in[,cols],bio.in[,cols])
all$input <- factor(all$input,levels=c("catch","lf","bio"))


fnames <- as_labeller(c(`catch` = "Débarquement / Landings (t)", `lf` = "Échantillons de fréquence de longueur (nombre) / Length-frequency samples (number)",`bio` = "Biologique (nombre de poissons) / Biological (number of fish)"))

p1 <- ggplot(all,aes(x=year,y=N,fill=gear))+
    geom_bar(stat='identity')+
    facet_wrap(input~.,scale='free_y',ncol=1,labeller = fnames)+
    scale_y_continuous(expand = c(0,0))+
    scale_x_continuous(expand = c(0,0), limits=c(1975,tail(my.year,1)+1))+
    scale_fill_viridis_d(na.value = "grey50")+
    theme(legend.position = 'top')+
    labs(x='Année/Year',y='',fill='Enging / Gear')
ggsave(paste0("../../img/", tail(my.year,1),"/Samples_gear.png"), width=8, height=6, dpi=600, units="in")

p2 <- ggplot(all,aes(x=year,y=N,fill=as.factor(period)))+
    geom_bar(stat='identity')+
    facet_wrap(input~.,scale='free_y',ncol=1,labeller = fnames)+
    scale_y_continuous(expand = c(0,0))+
    scale_x_continuous(expand = c(0,0), limits=c(1975,tail(my.year,1)+1))+
    scale_fill_viridis_d(na.value = "grey50")+
    theme(legend.position = 'top')+
    labs(x='Année/Year',y='',fill='Période / Period')
ggsave(paste0("../../img/", tail(my.year,1),"/Samples_period.png"), width=8, height=6, dpi=600, units="in")

p3 <- ggplot(all,aes(x=year,y=N,fill=region))+
    geom_bar(stat='identity')+
    facet_wrap(input~.,scale='free_y',ncol=1,labeller = fnames)+
    scale_y_continuous(expand = c(0,0))+
    scale_x_continuous(expand = c(0,0), limits=c(1975,tail(my.year,1)+1))+
    scale_fill_viridis_d(na.value = "grey50")+
    theme(legend.position = 'top')+
    labs(x='Année/Year',y='',fill='Région / Region')
ggsave(paste0("../../img/", tail(my.year,1),"/Samples_region.png"), width=8, height=6, dpi=600, units="in")

grid.arrange(p1,p2,p3,ncol=3)



sample_export <- rbind(lf.in[,cols],bio.in[,cols])
sample_export$input <- factor(sample_export$input,levels=c("lf","bio"))
fnamesexport <- as_labeller(c(`lf` = "Length-frequency samples (number)",`bio` = "Biological (number)"))
p3ex <- ggplot(sample_export,aes(x=year,y=N,fill=region))+
    geom_bar(stat='identity')+
    facet_wrap(input~.,scale='free_y',ncol=1,labeller = fnames)+
    scale_y_continuous(expand = c(0,0))+
    scale_x_continuous(expand = c(0,0), limits=c(1975,tail(my.year,1)+1))+
    scale_fill_viridis_d(na.value = "grey50")+
    theme(legend.position = 'right')+
    labs(x='',y='',fill='Region')
ggsave(paste0("../../img/", tail(my.year,1),"/Samples_EN.png"), width=8, height=4, dpi=600, units="in")


```


# CAA plots {.tabset}
## RAW
```{r caan_raw, message = F, fig.height = 3,fig.width = 10}
caa$zero <- caa$caan==0
ggplot(caa,aes(x=year,y=age))+
  geom_point(alpha=0.8,aes(size=caan,col=zero))+ 
  scale_size(range = c(1,12))+
  scale_y_continuous(breaks=min(caa$age):max(caa$age))+
  scale_color_manual(values=c('black','grey'))+
  labs(x='Year',y='Age',size='Numbers',col='Zero')
```

## SPAY
```{r caan_spay, message = F, fig.height = 3,fig.width = 10}
d <- reshape2::dcast(caa,age~year,value.var = 'caan')
if(length(unique(d$year)) >1){
d <- cbind(age=d[,1],spay(d[,-1]))
d <- reshape2::melt(d,id.vars='age',variable.name='year',value.name='caan')
d$year <- as.numeric(as.character(d$year))
ggplot(d,aes(x=year,y=age))+
  geom_point(alpha=0.8,aes(size=caan))+ 
  scale_size(range = c(1,12))+
  scale_y_continuous(breaks=min(caa$age):max(caa$age))
}
```

## SPAY: prop
```{r caan_prop, message = F, fig.height = 3,fig.width = 10}
d <- ddply(caa,c('year'),transform,caan.prop=caan/sum(caan))
CAA<- ggplot(d,aes(x=year,y=age))+
  geom_point(alpha=0.8,aes(size=caan.prop,col=zero))+ 
  scale_size(name="",range = c(1,12))+
  scale_y_continuous(breaks=min(caa$age):max(caa$age))+
  scale_color_manual(values=c('black','grey'), guide=F)


CAA +  labs(x='Year',y='Age',size='Proportion',col='Zero')
ggsave(paste0("../../img/",tail(my.year,1),"/CAA_EN.png"), width=8, height=4, dpi=600, units="in")

CAA +  labs(x='Année',y='Âge',size='Proportion',col='Zero')
ggsave(paste0("../../img/",tail(my.year,1),"/CAA_FR.png"), width=8, height=4, dpi=600, units="in")

CAA +  labs(x='Année | Year',y='Âge | Age',size='Proportion',col='Zero')
ggsave(paste0("../../img/",tail(my.year,1),"/CAA_BI.png"), width=8, height=4, dpi=600, units="in")

```


## SPYA
```{r caan_spya, message = F, fig.height = 3,fig.width = 10}
d <- reshape2::dcast(caa,age~year,value.var = 'caan')
d <- cbind(age=d[,1],spya(d[,-1]))
d <- reshape2::melt(d,id.vars='age',variable.name='year',value.name='caan')
d$year <- as.numeric(as.character(d$year))
ggplot(d,aes(x=year,y=age))+
  geom_point(alpha=0.8,aes(size=caan))+ 
  scale_size(range = c(1,12))+
  scale_y_continuous(breaks=min(caa$age):max(caa$age))
```

## SPYA: prop
```{r caan_spay_prop, message = F, fig.height = 3,fig.width = 10}
d <- ddply(caa,c('age'),transform,caan.prop=caan/sum(caan))
ggplot(d,aes(x=year,y=age))+
  geom_point(alpha=0.8,aes(size=caan.prop))+ 
  scale_size(range = c(1,12))+
  scale_y_continuous(breaks=min(caa$age):max(caa$age))
```

# WAA  {.tabset}

## linear interpol
```{r waa interpol, message = F, fig.height = 11,fig.width = 14}
caa.old <- expand.grid(year=1968:max(caa$year),age=unique(caa$age))
caa.inter <- merge(caa.old,caa,all=TRUE)
caa.inter <- caa.inter[order(caa.inter$age,caa.inter$year),]
par(mfrow=c(5,2))
caa.inter$waa.interpol <- ddply(caa.inter,c('age'),summarise,waa.interpol=interpol(year,waa,"linear",from = 1968,to=max(caa.inter$year),title = age[1])[,6])[,2]
caa.inter <- caa.inter[order(caa.inter$year,caa.inter$age,decreasing = F),]

write.csv(caa.inter,paste0('../../csv/',tail(my.year,1),'/caa_interpol.csv'),row.names = FALSE)
```

## Plot
```{r waa interpolplot, message = F, fig.height=3, fig.width=5}
p <- ggplot(caa.inter,aes(x=year,y=waa.interpol,col=as.factor(age)))+
    geom_line()+
    scale_color_viridis_d()+
    scale_x_continuous(expand=c(0,0))+
    labs(y='Poids des captures | Catch weight (kg)',x='Année | Year')+
    theme(legend.position = 'none')
p

p <- p+labs(y='Poids dans le captures (kg)',x='Année')
ggsave(paste0('waac_FR.png'),p,'png',paste0('../../img/', tail(my.year,1)),width = 15,height = 8,units = 'cm')

```


Try model smoothing. Not used because if changes to WAA, waa*caa does not equal total catch anymore.
# Model predictions
```{r waa_fit, message = F, fig.height = 11,fig.width = 10}
caa$waa.cv <- 0.01 # need to calculate this!! this is absurdly small value so all predictions will match observed
caa[caa$caaw==0,'caaw'] <- NA # should be correct in get.caa function
waa.fit <- with(caa, armatrix.fit(year=caa$year,age=caa$age,x=caa$waa,cv=caa$waa.cv))
waa.fit

caa$waa.cv <- with(caa,waa.sd/waa) # need to calculate this!! this is absurdly small value so all predictions will match observed
waa.fit <- armatrix.fit(year=caa$year,age=caa$age,x=caa$waa,cv=caa$waa.cv)
waa.fit
```

## Predicted
```{r waa_predobs, message = F, fig.height = 10,fig.width = 10}
armatrix.predobs(waa.fit,scale='free',ncol=3)
```

## Predicted
```{r waa_pred, message = F, fig.height = 10,fig.width = 10}
armatrix.pred(waa.fit,scale='free',ncol=3)
```

## Resid bubble
```{r waa_res, message = F, fig.height = 3,fig.width = 10}
armatrix.res(waa.fit)
```

## Resid dot
```{r waa_res2, message = F, fig.height = 10,fig.width = 10}
armatrix.res2(waa.fit)
```

## effects
```{r waa_effects, message = F, fig.height = 10,fig.width = 10}
armatrix.effects(waa.fit) # empty plot because of ggplotGrob function within (used to align plots)
```

## cvs
```{r waa_cv, message = F, fig.height = 10,fig.width = 10}
armatrix.cvs(waa.fit,scale='free',ncol=3)
```



