---
title: "Otoliths availability based on biological samples"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: show
    number_sections: TRUE
---
   
   
# SET-UP
```{r  markdown, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, fig.align = "center", fig.width = 9, fig.height = 6)
options(width = 140)
```    

## settings
```{r settings, message = F}
source('0.0_settings.R')
dir.create(paste0('../../csv/',tail(my.year,1),'/'),showWarnings = FALSE)
```

## load all data
```{r data, message = F}
load(paste0(dir.rdat, "bio.Rdata"))                                  # from 1.0 
#group.region <- read.table(paste0(dir.dat,'caa_group_region.txt'),header=T)

checko<- bio |>  
    mutate(region= if_else(nafo %in% c("4T", "4S"), "Gulf",
                                 if_else(prov=="NL" | nafo =="4R", "NL",
                                           if_else(prov=="NS" | nafo %in% c("4X", "4V"), "NS", NA)))) |> 

    filter(agef %in% c(0,1)) |> mutate(Q=quarter(date))
```

# Plot N bio data {.tabset}
## Overall age 1 or 0

```{r overall, message = F}
checkoa = checko |> 
    group_by(year) |>  tally()  |> 
    mutate(`check N > 50`= if_else(n>50,"\u2713", "X")) #|>  pivot_wider(values_from=n, names_from=region)

checkoa |>  ggplot(aes(x=year, y=n, fill=`check N > 50`)) +
    geom_bar(stat="identity", alpha=1, col="black",linewidth=0.1) + 
       scale_fill_manual(values=c("black", "grey"))+
    theme(legend.position="top")


```


## By age 

```{r age, message = F}
checko1 = checko |> 
    group_by(year,region, agef) |>  tally()  |> 
    mutate(`check N > 50`= if_else(n>50,"\u2713", "X")) #|>  pivot_wider(values_from=n, names_from=region)

checko1 |>  ggplot(aes(x=year, y=n, fill=`check N > 50`)) +
    geom_bar(stat="identity", alpha=1, col="black",linewidth=0.1) + 
    facet_grid(agef~region, scale="free") +
    scale_fill_manual(values=c("black", "grey"))+
    theme(legend.position="top")


```


## By region

```{r region, message = F}
checko2 = checko |> 
    group_by(year,region) |>  tally()  |> 
    mutate(`check N > 50`= if_else(n>50,"\u2713", "X")) #|>  pivot_wider(values_from=n, names_from=region)

checko2 |>  ggplot(aes(x=year, y=n, fill=`check N > 50`)) +
    geom_bar(stat="identity", alpha=1, col="black",linewidth=0.1) + 
    facet_wrap(~region)+
    scale_fill_manual(values=c("black", "grey"))+
    theme(legend.position="top") +
    ylab("N age 0 or 1")


```


## By region and quarters

```{r quarters, message = F}
checko3 = checko  |> 
    group_by(year,region, Q) |>  tally()  |> 
    mutate(`check N > 50`= if_else(n>50,"\u2713", "X")) #|>  pivot_wider(values_from=n, names_from=region)

checko3 |>  ggplot(aes(x=year, y=n, fill=`check N > 50`)) +
    geom_bar(stat="identity", alpha=1, col="black",linewidth=0.1) + 
    facet_grid(Q~region, scales="free_y")+
    scale_fill_manual(values=c("black", "grey"))+
    theme(legend.position="top") +
    ylab("N age 0 or 1")

```

## Priority

```{r gulf, message = F}
checko4 = checko  |> filter(region=="Gulf") |> 
    group_by(year,agef) |>  tally()  |> 
    mutate(`check N > 50`= if_else(n>50,"\u2713", "X")) #|>  pivot_wider(values_from=n, names_from=region)

checko4 |>  ggplot(aes(x=year, y=n, fill=`check N > 50`)) +
    geom_bar(stat="identity", alpha=1, col="black",linewidth=0.1) + 
    facet_wrap(~agef, scales="free_y")+
    scale_fill_manual(values=c("black", "grey"))+
    theme(legend.position="top") +
    ylab("N age 0 or 1")

```

# Tables 
```{r table1, message = F}
   vide<-  expand_grid(year=unique(checko$year),   
                region=unique(checko$region),
                agef=unique(checko$agef),
                Q=unique(checko$Q))

left_join(vide, checko |> group_by(year,region, agef, Q) |>  tally()) |> 
    mutate(n=replace_na(n, 0)) |> arrange(year, region, agef, Q) |> 
    
DT::datatable(class="cell-border stripe", rownames = F, filter="top",
                      editable=T, extensions="Buttons", options=list(dom="Bftrop", buttons=c("copy", "csv","excel","pdf", "print"),autoWidth=T, scrollX=T)) 
      

```
